storage:
  s3:
    endpoint: ${S3_ENDPOINT:http://localhost:9000}
    region: ${S3_REGION:ap-northeast-2}
    bucket: ${S3_BUCKET:woobeee}
    access-key: ${S3_ACCESS_KEY:admin}
    secret-key: ${S3_SECRET_KEY:admin!23}
    presigned-url-expiration-seconds: 600
    path-style-access-enabled: true

server:
  shutdown: graceful
  port: 8001

spring:
  application:
    name: woobeee-app-webflux
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:9379}
      password: ${REDIS_PASSWORD:root!23}
  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://localhost:9432/market}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456789}
    pool:
      initial-size: 5
      max-size: 30
  flyway:
    enabled: false

logging:
  file:
    name: logs/app-webflux.log
