-- 할 일 시간 입력(선택)과 시작 전 Slack 알림 (SCHEDULE-AC-34 ~ 36).
-- 날짜 컬럼은 그대로 두고 시간만 더한다 — 달력·자동 완료·다이제스트는 start_date/end_date 로 계속 돈다.
ALTER TABLE tasks ADD COLUMN start_time TIME, ADD COLUMN end_time TIME;

-- 발송 여부를 행에 남겨 재시작 후 중복 발송을 막는다. FK 없음: 서비스 계층이 캐스케이드한다.
CREATE TABLE task_reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    minutes_before INT NOT NULL CHECK (minutes_before IN (10, 30)),
    sent_at TIMESTAMP(6),
    UNIQUE (task_id, minutes_before)
);
CREATE INDEX idx_task_reminders_task_id ON task_reminders (task_id);
