-- 상태에 보류(ON_HOLD)·오류(ERROR) 추가 (SCHEDULE-AC-38). 세 테이블의 CHECK 제약을 5값으로 재생성한다.
-- 제약 이름은 V8 의 컬럼 인라인 CHECK 가 받은 Postgres 기본 이름(<table>_status_check)이다.
ALTER TABLE projects DROP CONSTRAINT projects_status_check;
ALTER TABLE projects ADD CONSTRAINT projects_status_check
    CHECK (status IN ('NOT_STARTED', 'IN_PROGRESS', 'DONE', 'ON_HOLD', 'ERROR'));

ALTER TABLE milestones DROP CONSTRAINT milestones_status_check;
ALTER TABLE milestones ADD CONSTRAINT milestones_status_check
    CHECK (status IN ('NOT_STARTED', 'IN_PROGRESS', 'DONE', 'ON_HOLD', 'ERROR'));

ALTER TABLE tasks DROP CONSTRAINT tasks_status_check;
ALTER TABLE tasks ADD CONSTRAINT tasks_status_check
    CHECK (status IN ('NOT_STARTED', 'IN_PROGRESS', 'DONE', 'ON_HOLD', 'ERROR'));

-- 할 일 밑의 이슈사항 (SCHEDULE-AC-40 ~ 42). 달력에는 나오지 않고 할 일 행 아래에 접혀 있다.
-- FK 없음: 기존 관례대로 서비스 계층이 캐스케이드한다. 소유권은 부모 할 일의 member_id 로 판별한다.
CREATE TABLE task_issues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    content VARCHAR(1000) NOT NULL,
    resolved BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6)
);
CREATE INDEX idx_task_issues_task_id ON task_issues (task_id);
