-- 글 태그 (BLOG-AC-18 ~ 22). FK 없음: 참조 무결성은 애플리케이션이 검사한다(글 삭제 시 post_tags 부터 지운다).
-- 이름 비교는 대소문자 무시 — lower(name) 유니크 인덱스가 중복 태그를 막고, 표기는 처음 저장된 그대로 남는다.
CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);
CREATE UNIQUE INDEX ux_tags_name_lower ON tags (lower(name));

CREATE TABLE post_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    UNIQUE (post_id, tag_id)
);
CREATE INDEX idx_post_tags_tag_id ON post_tags (tag_id);
