-- 포켓몬 포켓코인 공동구매 신청서.
-- 환율은 신청 시점 값을 행에 스냅샷으로 박는다 — 이체해야 할 금액의 근거가 되어야 하므로
-- 조회할 때마다 다시 계산하면 안 된다. 현재 환율과의 차이는 읽는 쪽에서 계산한다.
CREATE TABLE pokemon_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 로그인 신청이면 채워지고, 비회원 신청이면 NULL 이다.
    member_id BIGINT,
    -- 로그인이면 회원 닉네임, 비회원이면 직접 입력한 이름.
    applicant_name VARCHAR(60) NOT NULL,
    -- 입금자명이 신청자와 다를 때만 채운다. 계좌 내역 대조용.
    depositor_name VARCHAR(60),
    status VARCHAR(20) NOT NULL DEFAULT 'REQUESTED'
        CHECK (status IN ('REQUESTED', 'DEPOSITED', 'SHIPPING', 'DELIVERED', 'CANCELLED')),
    -- 상품 합계(루피). 항목 단가 스냅샷의 합이다.
    total_inr NUMERIC(12, 2) NOT NULL CHECK (total_inr > 0),
    -- 신청 시점의 INR -> KRW 환율과 그 환율의 기준 시각.
    quoted_rate NUMERIC(14, 6) NOT NULL CHECK (quoted_rate > 0),
    quoted_at TIMESTAMP(6) NOT NULL,
    -- round(total_inr * quoted_rate). 기부금을 뺀 상품값만.
    items_krw BIGINT NOT NULL CHECK (items_krw >= 0),
    -- 선택 기부금(원화). 0 이면 기부 없음.
    donation_krw BIGINT NOT NULL DEFAULT 0 CHECK (donation_krw >= 0),
    -- items_krw + donation_krw. 신청자가 실제로 이체해야 하는 금액.
    transfer_krw BIGINT NOT NULL CHECK (transfer_krw >= 0),
    -- 인도 스토어에서 실제로 결제한 시점의 환율. SHIPPING(= 결제를 마치고 배달을 시작)으로
    -- 넘어갈 때 한 번 박히고 그 뒤로 환차손익이 확정된다. 그 전까지는 NULL 이고
    -- 손익은 현재 환율로 평가한다.
    settled_rate NUMERIC(14, 6) CHECK (settled_rate IS NULL OR settled_rate > 0),
    settled_at TIMESTAMP(6),
    memo VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6)
);

CREATE TABLE pokemon_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES pokemon_orders (id) ON DELETE CASCADE,
    product VARCHAR(20) NOT NULL,
    -- 상품표가 바뀌어도 과거 신청 금액이 따라 움직이면 안 된다 — 당시 값을 박는다.
    coins INT NOT NULL CHECK (coins > 0),
    unit_price_inr NUMERIC(10, 2) NOT NULL CHECK (unit_price_inr > 0),
    quantity INT NOT NULL CHECK (quantity > 0)
);

CREATE INDEX idx_pokemon_orders_member ON pokemon_orders (member_id);
CREATE INDEX idx_pokemon_orders_status ON pokemon_orders (status);
CREATE INDEX idx_pokemon_order_items_order ON pokemon_order_items (order_id);

-- 신청서에 달리는 댓글. 신청과 마찬가지로 비회원도 쓸 수 있으므로 member_id 는 NULL 가능이다.
CREATE TABLE pokemon_order_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES pokemon_orders (id) ON DELETE CASCADE,
    member_id BIGINT,
    author_name VARCHAR(60) NOT NULL,
    content VARCHAR(500) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_pokemon_order_comments_order ON pokemon_order_comments (order_id);
