-- 상품표를 코드(enum)에서 DB 로 옮긴다. App Store 의 In-App Purchases 목록을 매일 긁어
-- 갱신하므로 배포 없이 바뀌어야 하기 때문이다.
CREATE TABLE pokemon_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 스토어에 적힌 이름 그대로. 이것이 동기화의 식별자다 — 스토어는 상품 id 를 노출하지 않는다.
    name VARCHAR(200) NOT NULL UNIQUE,
    price_inr NUMERIC(10, 2) NOT NULL CHECK (price_inr > 0),
    -- 이름에서 뽑은 포켓코인 수. 이벤트 티켓처럼 코인이 아닌 상품은 0 이다.
    coins INT NOT NULL DEFAULT 0 CHECK (coins >= 0),
    sort_order INT NOT NULL DEFAULT 0,
    -- 스토어 목록에서 사라진 상품은 지우지 않고 내린다. 과거 신청서가 가리키고 있고,
    -- 한 번의 파싱 실패로 목록이 통째로 날아가면 안 된다.
    active BOOLEAN NOT NULL DEFAULT TRUE,
    first_seen_at TIMESTAMP(6) NOT NULL,
    last_seen_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6)
);

CREATE INDEX idx_pokemon_products_active ON pokemon_products (active, sort_order);

-- 2026-09-29 apps.apple.com/in/app/pokemon-go/id1094591345 에서 읽은 값으로 시작한다.
-- 동기화가 처음 돌기 전에도 화면이 비어 있지 않게 하려는 것이다.
INSERT INTO pokemon_products (name, price_inr, coins, sort_order, first_seen_at, last_seen_at)
VALUES ('100 PokéCoins',        29.00,   100,   1, now(), now()),
       ('550 PokéCoins',        149.00,  550,   2, now(), now()),
       ('1,200 PokéCoins',      289.00,  1200,  3, now(), now()),
       ('2,500 PokéCoins',      589.00,  2500,  4, now(), now()),
       ('5,200 PokéCoins',      1169.00, 5200,  5, now(), now()),
       ('14,500 PokéCoins',     2899.00, 14500, 6, now(), now()),
       ('Event Ticket',         59.00,   0,     7, now(), now()),
       ('Event Ticket Giftable', 59.00,  0,     8, now(), now()),
       ('Event Pass 3 Deluxe',  229.00,  0,     9, now(), now()),
       ('Event Pass Deluxe',    229.00,  0,    10, now(), now());

-- 주문 항목은 enum 이름 대신 상품 참조 + 당시 이름 스냅샷을 든다.
-- 상품이 내려가거나 이름이 바뀌어도 과거 신청서가 무엇을 샀는지 읽을 수 있어야 한다.
ALTER TABLE pokemon_order_items
    ADD COLUMN product_id BIGINT REFERENCES pokemon_products (id);
ALTER TABLE pokemon_order_items
    ALTER COLUMN product TYPE VARCHAR(200);
ALTER TABLE pokemon_order_items
    RENAME COLUMN product TO product_name;
