CREATE TABLE IF NOT EXISTS buyers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_subject VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    nickname VARCHAR(60) NOT NULL,
    terms_agreed BOOLEAN NOT NULL,
    privacy_policy_agreed BOOLEAN NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS sellers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_subject VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    nickname VARCHAR(60) NOT NULL,
    terms_agreed BOOLEAN NOT NULL,
    privacy_policy_agreed BOOLEAN NOT NULL,
    business_registration_certificate_url VARCHAR(1000),
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    recipient_name VARCHAR(255),
    phone_number VARCHAR(255),
    zipcode VARCHAR(255),
    address1 VARCHAR(255),
    address2 VARCHAR(255),
    is_default BOOLEAN NOT NULL,
    created_at TIMESTAMP(6),
    member_id BIGINT
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_ko VARCHAR(255),
    name_en VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    parent_id BIGINT
);

CREATE TABLE IF NOT EXISTS posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_ko VARCHAR(255),
    title_en VARCHAR(255),
    text_ko TEXT,
    text_en TEXT,
    views BIGINT,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    category_id BIGINT,
    member_id BIGINT,
    member_role VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    post_id BIGINT,
    parent_id BIGINT,
    member_id BIGINT,
    member_role VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT,
    member_role VARCHAR(255),
    post_id BIGINT,
    created_at TIMESTAMP(6),
    CONSTRAINT uk_likes_member_post UNIQUE (member_id, member_role, post_id)
);

CREATE INDEX IF NOT EXISTS idx_categories_parent_id ON categories (parent_id);
CREATE INDEX IF NOT EXISTS idx_posts_category_id ON posts (category_id);
CREATE INDEX IF NOT EXISTS idx_posts_member ON posts (member_id, member_role);
CREATE INDEX IF NOT EXISTS idx_comments_post_id ON comments (post_id);
CREATE INDEX IF NOT EXISTS idx_comments_parent_id ON comments (parent_id);
CREATE INDEX IF NOT EXISTS idx_likes_post_id ON likes (post_id);
