-- 공동구매를 "차수" 단위로 연다. 여는 사람이 그 차수의 주최자이고, 주최자마다 URL 이 갈린다
-- (/pokemon/{handle}). 통화도 차수가 고른다 — 인도 스토어면 INR, 미국이면 USD.

-- 주최자의 URL 조각. 회원당 하나이고 바꾸면 이전 주소가 죽으므로 신중히 고르게 한다.
-- members 에 붙이지 않는 이유: auth 도메인을 pokemon 사정으로 넓히지 않는다.
CREATE TABLE pokemon_hosts (
    member_id  BIGINT PRIMARY KEY,
    handle     VARCHAR(30) NOT NULL UNIQUE
        CHECK (handle ~ '^[a-z0-9][a-z0-9-]{1,29}$'),
    created_at TIMESTAMP(6) NOT NULL
);

-- 상품표는 주최자마다 따로다. 스토어(통화)가 다르면 가격도 다르고, 주최자끼리 서로의
-- 상품을 건드리면 안 된다. 그래서 (주최자, 이름, 통화)가 유일하다 — 홍석의 "100 PokéCoins"
-- 와 병우의 것은 별개다.
ALTER TABLE pokemon_products ADD COLUMN host_member_id BIGINT;
ALTER TABLE pokemon_products ADD COLUMN currency VARCHAR(3) NOT NULL DEFAULT 'INR';
ALTER TABLE pokemon_products RENAME COLUMN price_inr TO price;

-- 지금까지의 상품표는 운영자(1)의 것으로 옮긴다.
UPDATE pokemon_products SET host_member_id = 1 WHERE host_member_id IS NULL;
ALTER TABLE pokemon_products ALTER COLUMN host_member_id SET NOT NULL;

ALTER TABLE pokemon_products DROP CONSTRAINT pokemon_products_name_key;
ALTER TABLE pokemon_products ADD CONSTRAINT pokemon_products_host_name_currency_key
    UNIQUE (host_member_id, name, currency);
CREATE INDEX idx_pokemon_products_host ON pokemon_products (host_member_id, active, sort_order);

CREATE TABLE pokemon_rounds (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_member_id   BIGINT NOT NULL,
    -- 주최자 안에서 1차, 2차, 3차. 주최자가 다르면 번호가 겹쳐도 된다.
    sequence         INT NOT NULL CHECK (sequence > 0),
    title            VARCHAR(100),
    currency         VARCHAR(3) NOT NULL,
    -- 환율을 어떻게 잡을지 주최자가 고른다.
    --   FIXED     : 아래 quoted_rate 로 고정. 한 차수 안에서 모두 같은 환율을 쓴다
    --   PER_ORDER : 신청서마다 그 시점 환율. 오래 열어 두는 차수에 맞다
    rate_mode        VARCHAR(20) NOT NULL DEFAULT 'FIXED'
        CHECK (rate_mode IN ('FIXED', 'PER_ORDER')),
    -- 1 <currency> = N KRW. FIXED 일 때 쓰는 값이고 주최자가 직접 고칠 수 있다.
    -- 고쳐도 이미 들어온 신청서는 각자 박아 둔 환율을 유지한다 — 알려 준 이체 금액이
    -- 나중에 달라지면 안 된다.
    quoted_rate      NUMERIC(14, 6) NOT NULL CHECK (quoted_rate > 0),
    quoted_at        TIMESTAMP(6) NOT NULL,
    -- 주최자마다 계좌가 다르므로 차수가 들고 있다.
    bank_account     VARCHAR(200) NOT NULL,
    deadline         DATE,
    status           VARCHAR(20) NOT NULL DEFAULT 'OPEN'
        CHECK (status IN ('OPEN', 'CLOSED', 'PURCHASED', 'DELIVERED', 'CANCELLED')),
    -- 주최자가 실제로 결제한 시점의 환율. PURCHASED 로 처음 넘어갈 때 박히고 환차손익이 확정된다.
    settled_rate     NUMERIC(14, 6) CHECK (settled_rate IS NULL OR settled_rate > 0),
    settled_at       TIMESTAMP(6),
    memo             VARCHAR(500),
    created_at       TIMESTAMP(6) NOT NULL,
    updated_at       TIMESTAMP(6),
    UNIQUE (host_member_id, sequence)
);

CREATE INDEX idx_pokemon_rounds_host ON pokemon_rounds (host_member_id, sequence DESC);
CREATE INDEX idx_pokemon_rounds_status ON pokemon_rounds (status);

-- 신청서는 차수에 속한다.
ALTER TABLE pokemon_orders ADD COLUMN round_id BIGINT REFERENCES pokemon_rounds (id);

-- 차수가 생기기 전에 들어온 신청서를 "이전 신청서" 차수 하나로 묶는다.
--
-- 이 블록은 컬럼 이름을 바꾸거나 지우기 **전에** 돌아야 한다. 신청서가 각자 들고 있던
-- settled_rate 를 차수로 옮겨야 하는데, 먼저 DROP 하면 옮길 값이 이미 없다.
DO $$
DECLARE
    -- 차수가 없던 시절의 공동구매는 운영자가 굴렸다.
    legacy_host  BIGINT := 1;
    legacy_id    BIGINT;
    legacy_handle VARCHAR(30);
    carried_rate NUMERIC(14, 6);
    carried_at   TIMESTAMP(6);
    legacy_status VARCHAR(20);
BEGIN
    IF EXISTS (SELECT 1 FROM pokemon_orders WHERE round_id IS NULL) THEN
        -- 결제 환율을 차수 하나로 모은다. 총액 가중평균이라 합계가 그대로 보존된다
        -- (단순 평균은 큰 신청서를 과소평가해 환차손익이 어긋난다).
        SELECT SUM(settled_rate * total_inr) / NULLIF(SUM(total_inr), 0), MAX(settled_at)
          INTO carried_rate, carried_at
          FROM pokemon_orders
         WHERE round_id IS NULL AND settled_rate IS NOT NULL;

        -- 결제까지 갔던 흔적이 있으면 구매완료, 아니면 마감으로 둔다. 배달까지 끝났는지는
        -- 알 수 없으므로 단정하지 않고 주최자가 직접 올리게 한다.
        legacy_status := CASE WHEN carried_rate IS NULL THEN 'CLOSED' ELSE 'PURCHASED' END;

        -- 주최자에게 주소가 없으면 차수 URL(/pokemon/{handle}/{n})이 만들어지지 않아
        -- 옮긴 신청서에 영영 닿지 못한다. 없으면 여기서 만들어 준다.
        SELECT handle INTO legacy_handle FROM pokemon_hosts WHERE member_id = legacy_host;
        IF legacy_handle IS NULL THEN
            INSERT INTO pokemon_hosts (member_id, handle, created_at)
            VALUES (legacy_host, 'host-' || legacy_host, now());
        END IF;

        INSERT INTO pokemon_rounds (host_member_id, sequence, title, currency, rate_mode,
                                    quoted_rate, quoted_at, bank_account, status,
                                    settled_rate, settled_at, memo, created_at)
        SELECT legacy_host, 1, '이전 신청서', 'INR',
               -- 신청서마다 환율이 달랐으므로 PER_ORDER 다. 각 신청서의 quoted_rate 를
               -- 그대로 쓰게 되어 이미 알려 준 이체 금액이 흔들리지 않는다.
               'PER_ORDER',
               COALESCE(AVG(quoted_rate), 1), now(),
               '이전 신청서 — 주최자가 계좌를 채워 주세요', legacy_status,
               carried_rate, carried_at,
               '차수 기능이 생기기 전에 들어온 신청서를 옮긴 것입니다.', now()
          FROM pokemon_orders WHERE round_id IS NULL
        RETURNING id INTO legacy_id;

        UPDATE pokemon_orders SET round_id = legacy_id WHERE round_id IS NULL;
    END IF;
END $$;

ALTER TABLE pokemon_orders ALTER COLUMN round_id SET NOT NULL;
CREATE INDEX idx_pokemon_orders_round ON pokemon_orders (round_id);

-- 금액 컬럼은 통화 중립 이름으로 바꾼다 — 더 이상 루피만이 아니다. 이름만 바뀌고 값은 그대로다.
ALTER TABLE pokemon_orders RENAME COLUMN total_inr TO total_amount;
ALTER TABLE pokemon_orders RENAME COLUMN extra_inr TO extra_amount;
ALTER TABLE pokemon_order_items RENAME COLUMN unit_price_inr TO unit_price;

-- "준비중" 과 결제 환율은 차수로 올라갔다. 신청서에 남는 것은 주문/입금확인/전달완료뿐이다.
ALTER TABLE pokemon_orders DROP CONSTRAINT pokemon_orders_status_check;
UPDATE pokemon_orders SET status = 'DEPOSIT_CONFIRMED' WHERE status = 'PREPARING';
ALTER TABLE pokemon_orders ADD CONSTRAINT pokemon_orders_status_check
    CHECK (status IN ('ORDERED', 'DEPOSIT_CONFIRMED', 'DELIVERED', 'CANCELLED'));

-- 위 블록이 차수로 옮겨 놓은 뒤라 지워도 잃는 것이 없다.
ALTER TABLE pokemon_orders DROP COLUMN settled_rate;
ALTER TABLE pokemon_orders DROP COLUMN settled_at;
