CREATE TABLE game_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_type VARCHAR(20) NOT NULL,
    room_id VARCHAR(40) NOT NULL,
    started_at TIMESTAMP(6) NOT NULL,
    ended_at TIMESTAMP(6) NOT NULL,
    winner_participant_id VARCHAR(64),
    replay_object_key VARCHAR(1000),
    created_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE game_result_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_result_id BIGINT NOT NULL,
    participant_id VARCHAR(64) NOT NULL,
    display_name VARCHAR(60) NOT NULL,
    member_id BIGINT,
    finish_rank INT NOT NULL
);

CREATE INDEX idx_game_results_ended_at ON game_results (ended_at DESC);
CREATE INDEX idx_game_result_participants_result ON game_result_participants (game_result_id);
CREATE INDEX idx_game_result_participants_member ON game_result_participants (member_id);
